[package]
name = "day02"
version = "0.1.0"
authors = ["Michael Mario Kubicki <contact@michael-kubicki.de>"]
edition = "2018"
license = "MIT"

[dependencies]
structopt = "0.3"

common = { path = "../common" }
